#!/usr/bin/env bash

# Calls UACP API to have the repo content pulled into the CMS
# Takes two parameters:
# - repo git URL (https schema) (mandatory)
# - the dir containing the docs (optional, defaults to 'docs')

# Requires the UACP ingress URL to be set in env var UACP_INGRESS_URL.

declare URL=${UACP_INGRESS_URL:?UACP ingress URL not set}

usage() {

  local self=$1
  echo "Usage: $self <repo-git-url> <documentation-dir>"

}

calluacp() {

  local url=$1
  local path=${2:-docs}

  echo "URL is $URL"

  curl \
    --fail \
    --location \
    --form 'repository="'"$url"'"' \
    --form 'path="'"$path"'"' \
    "$URL"

}

main() {

  local self
  self="$(basename "$0")"
  [[ $# == 0 ]] && usage "$self" && exit 1

  calluacp "$@"

}

main "$@"
