name: Build and push to UACP
on: [push, workflow_dispatch]
env:
  UACP_USER: ${{ secrets.UACP3_USER }}
  UACP_PASS: ${{ secrets.UACP3_PASS }}
jobs:
  main:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: ./send-to-uacp
