name: Build and push to UACP
on: [workflow_dispatch]
env:
  UACP_USER: ${{ secrets.UACP3_USER }}
  UACP_PASS: ${{ secrets.UACP3_PASS }}
jobs:
  main:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - run: |
        node -v
        npm -v
