name: github-to-uacp
on:
  push:
  workflow_dispatch:
    inputs:
      path:
        description: Where the documentation sources are in this repository
        required: true
        default: docs
jobs:
  main:
    runs-on: self-hosted
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo REPOSITORY URL
          echo github.repositoryUrl ${{ github.repositoryUrl }}
          echo github.event.repository.clone_url ${{ github.event.repository.clone_url }}
