name: github-to-uacp
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Make UACP API call
        run: ./github-to-uacp "${{ github.event.repository.clone_url }}" "docs"
