name: github-to-uacp
on:
  push:
  workflow_dispatch:
    inputs:
      path:
        description: Where the documentation sources are in this repository
        required: true
        default: docs
jobs:
  main:
    runs-on: self-hosted
    steps:
      - name: Make UACP API call
        run: |
          echo \
            --location \
            --request POST \
            --form 'repository="${{ github.event.repository.clone_url }}"' \
            --form 'path="${{ github.event.inputs.path }}"' \
            'https://api.ingress.uacp-services.uacp.shoot.canary.k8s-hana.ondemand.com/github-to-uacp'
