name: github-to-uacp
on:
  push:
  workflow_dispatch:
    inputs:
      path:
        description: Where the documentation sources are in this repository
        required: true
        default: docs
jobs:
  main:
    runs-on: self-hosted
    steps:
      - name: Make UACP API call
        run: |
          inputs_path=${{ github.event.inputs.path }}
          FORM_PATH=${inputs_path:-docs}
          echo FORM_PATH is "$FORM_PATH"
          echo
            --location \
            --request POST \
            --form 'repository="${{ github.event.repository.clone_url }}"' \
            --form 'path="$FORM_PATH"' \
            'https://api.ingress.uacp-services.uacp.shoot.canary.k8s-hana.ondemand.com/github-to-uacp'
