name: Merged pull request labeler

# What the execution context is:
# The merging (not just closing) of a pull request.

# What it does:
# Assigns the 'valuable contribution' label.

# Why we need it:
# To mark a valuable pull request contribution, and thus to cause the
# SAP Community profile URL requester to be triggered.

# What's important to know:
# In order to have this workflow trigger another, a PAT is required,
# rather than a regular token. The label to assign is defined at the
# start of the job, in the LABEL environment variable.

on:
  pull_request_target:
    types: [closed]

jobs:

  assign-label-on-merge:
    if: contains(github.repositoryUrl, 'github.com') && github.event.pull_request.merged
    env:
      LABEL: "contribution"
    runs-on: ubuntu-20.04

    steps:

      - id: token_gen
        name: Generate app installation token
        uses: machine-learning-apps/actions-app-token@0.21
        with:
          APP_PEM: ${{ secrets.SAP_CODOC_APP_PEM_BASE64 }}
          APP_ID: ${{ secrets.SAP_CODOC_APP_ID }}

      - id: checkout
        name: Check out the repo
        uses: actions/checkout@v2
        with:
          token: ${{ steps.token_gen.outputs.app_token }}

      - id: auth_gh
        name: Authenticate gh to repo
        run: echo -n ${{ steps.token_gen.outputs.app_token }} | gh auth login --with-token

      - id: assign_label
        run: gh pr edit ${{ github.event.number }} --add-label "$LABEL"
